model_config:
  embedding_dim_conv: 1536
  conv_kernel_size: 9
  conv_mixer_repetition: 20
  patch_size: 14
  embedding_dim_trans: 512
  n_head: 8
  squeeze_ratio: 1
  transformer_encoder_repetition: 5
  dropout: 0.25 # default 0.2
  num_register: 1 ## To s
  multiplication_factor: 2
  output_classes: 1000

trainer_config:
  compile_model: False
  #snapshot_path: "/model"
  save_every: 1
  #total_epochs: 300
  
  
optimizer_scheduler_config:
  optimizer_config:
    lr: 0.003
    weight_decay: 0.009

  scheduler_config:
    cosine:
      T_0: 300
      eta_min: 0.0000088
    constant_scheduler:
      factor: 0.0001
      total_iters: 2
    linear_scheduler:
      total_iters: 5
      start_factor: 0.0002
  
data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   root_dir: "/home/sahmaran/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/val"
   csv_file: "~/Desktop/ImageNet/LOC_val_solution.csv"
  train_data_details:
   batch_size: 64
   num_workers: 8
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 2
   
  val_data_details:
   batch_size: 32
   num_workers: 4
   pin_memory: True
   drop_last: True
  
  
