model_config:
  embedding_dim_conv: 128
  conv_kernel_size: 7
  conv_mixer_repetition: 2
  patch_size: 14
  embedding_dim_trans: 128
  n_head: 8
  squeeze_ratio: 1
  transformer_encoder_repetition: 2
  dropout: 0.20 # default 0.2
  num_register: 1 ## To s
  multiplication_factor: 4 ## NN after attention layers!!!
  output_classes: 1000

trainer_config:
  compile_model: False
  snapshot_dir: "model"
  snapshot_name: "model_1.pt"
  save_every: 1
  total_epochs: 300
  
  
optimizer_scheduler_config:
  optimizer_config:
    lr: 0.001
    weight_decay: 0.03

  scheduler_config:
    cosine:
      T_0: 300
      eta_min: 0.0000088
    constant_scheduler:
      factor: 0.0001
      total_iters: 2
    linear_scheduler:
      total_iters: 5
      start_factor: 0.0002
  
data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   root_dir: "/home/sahmaran/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/val"
   csv_file: "~/Desktop/ImageNet/LOC_val_solution.csv"
  train_data_details:
   batch_size: 128
   num_workers: 6
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 2
   
  val_data_details:
   batch_size: 32
   num_workers: 4
   pin_memory: True
   drop_last: True
  
  
