model_config:
  embedding_dim: 768
  conv_kernel_size: 7
  conv_mixer_repetition: 15
  patch_size: 14
  dropout_mlp: 0.0 # default 0.2
  multiplication_factor: 2 ## NN after attention layers!!!
  output_classes: 1000
  cheap: True
trainer_config:
  compile_model: False
  snapshot_dir: "model_conv"
  snapshot_name: "model_1.pt"
  save_every: 1
  total_epochs: 300
## Check the variance of the weights
## All conv, linear and transformer blocks.
## initialize the weights more carefully   
  
optimizer_scheduler_config:
  optimizer_config:
    lr: 0.0001875  #0.0005*batch_size*GPU/512
    weight_decay: 0.05

  scheduler_config:
    cosine:
      T_0: 300
      eta_min: 0.0000088
    constant_scheduler:
      factor: 0.0001
      total_iters: 2
    linear_scheduler:
      total_iters: 5
      start_factor: 0.0002
  
data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   root_dir: "/home/sahmaran/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/val"
   csv_file: "~/Desktop/ImageNet/LOC_val_solution.csv"
  train_data_details:
   batch_size: 48
   num_workers: 8
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 2
   
  val_data_details:
   batch_size: 32
   num_workers: 4
   pin_memory: True
   drop_last: True
  

