model_config:
  embedding_dim_conv: 512
  n_head: 4
  conv_kernel_size: 7
  conv_mixer_repetition: 5
  transformer_encoder_repetition: 5
  patch_size: 8
  dropout: 0.2
  num_register: 2
  multiplication_factor: 2
  squeeze_ratio: 1

compile_model: True
snapshot_path: "/model"
save_every: 1
epochs: 200

optimizer_config:
  lr: 0.00001
  weight_decay: 0.0005

scheduler_config:
  T_max: 12

data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   root_dir: "/home/sahmaran/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/val"
   csv_file: "~/Desktop/ImageNet/LOC_val_solution.csv"
  train_data_details:
   batch_size: 16
   num_workers: 4
   pin_memory: True
   
  val_data_details:
   batch_size: 16
   num_workers: 2
   pin_memory: True
   drop_last: True
