
model_config:
  embedding_dim_conv: 512

  n_head: 4
  conv_kernel_size: 5
  conv_mixer_repetition: 5
  transformer_encoder_repetition: 5
  patch_size: 16
  dropout: 0.2
  num_register: 2
  multiplication_factor: 1
  squeeze_ratio: 1



compile_model: False
snapshot_path: "/model"
save_every: 1
epochs: 1

  
optimizer_config:
  lr: 0.000001
  weight_decay: 0.00001
  momentum: 0.99

scheduler_config:
  T_max: 15

data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   file: "array_test.dat"
   length_file: "lengthsarray_test.dat"
   lags: 513
  
  train_data_details:
   batch_size: 32
   num_workers: 4
   shuffle: True
   pin_memory: True
   
  val_data_details:
   batch_size: 32
   num_workers: 2
   shuffle: False
   pin_memory: True
   drop_last: True
   
   
   
  

