model_config:
  embedding_dim_conv: 512
  embedding_dim_trans: 128
  n_head: 4
  conv_kernel_size: 7
  conv_mixer_repetition: 5
  squeeze_ratio: 2
  transformer_encoder_repetition: 10
  patch_size: 14
  dropout: 0.2 # default 0.2
  num_register: 5
  multiplication_factor: 1
  output_classes: 1000

trainer_config:
  compile_model: False
  #snapshot_path: "/model"
  save_every: 1
  #epochs: 200

optimizer_config:
  lr: 0.0001
  weight_decay: 0.005

scheduler_config:
  T_max: 9
  eta_min: 0.000001

data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   root_dir: "/home/sahmaran/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/val"
   csv_file: "~/Desktop/ImageNet/LOC_val_solution.csv"
  train_data_details:
   batch_size: 64
   num_workers: 6
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 3
   
  val_data_details:
   batch_size: 64
   num_workers: 4
   pin_memory: True
   drop_last: True
