wandb_config:
  project: "SdPNet"
  group: "XL"

model_config:
  num_blocks: 15
  embedding_dim: 768
  n_head: 16
  ff_multiplication_factor: 4
  conv_kernel_size: 7
  patch_size: 16
  ffn_dropout: 0.3
  attn_dropout: 0.3
  stochastic_depth: False
  stochastic_depth_p: [0.2, 0.1]
  output_classes: 1000
  max_image_size: [16,16]
  max_num_registers: 5
  conv_first: False
  head_output_from_register: True
  simple_mlp_output: False
  output_head_bias: False
  normalize_qv: True


trainer_config:
  compile_model: False
  snapshot_dir: "model"
  snapshot_name: "model_1.pt"
  save_every: 1
  total_epochs: 300
  gradient_accumulation_steps: 1
  report_every_epoch: 1
  use_cross_entropy: False #True for cross entropy False for BCEloss
  
  
optimizer_scheduler_config:
  optimizer_config:
    lr: 0.001  #0.0005*batch_size*gradient_accumulation_steps*GPU/512
    weight_decay: 0.05

  scheduler_config:
    cosine:
      T_0: 300
      eta_min: 0.0000088
    constant_scheduler:
      factor: 0.001
      total_iters: 2
    linear_scheduler:
      total_iters: 5
      start_factor: 0.001
  
data:
  Num_Classes: 1000
  train_image_size: [224, 224]
  val_image_size: [320, 320]
  val_crop_size: [224, 224]


  train_data_details:
   batch_size: 384 #0.005*batch_size*grad_accumulation_step*gpu/512
   num_workers: 12
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 4
   drop_last: True
   
   
  val_data_details:
   batch_size: 128
   num_workers: 4
   pin_memory: True
   drop_last: True
  
  
