
model_config:
  number_ts: 264
  embedding_dim: 512
  n_blocks: 12
  pool_size: 4
  number_of_heads: 4



compile_model: False
snapshot_path: "/model"
save_every: 1
epochs: 1
local_rank: "0"
  
optimizer_config:
  lr: 0.000001
  weight_decay: 0.00001
  momentum: 0.99

scheduler_config:
  T_max: 15

data:
  train_path:
   file: "array_train.dat"
   length_file: "lengthsarray_train.dat"
   lags: 513
  val_path:
   file: "array_test.dat"
   length_file: "lengthsarray_test.dat"
   lags: 513
  
  train_data_details:
   batch_size: 32
   num_workers: 4
   shuffle: True
   pin_memory: True
  val_data_details:
   batch_size: 32
   num_workers: 2
   shuffle: False
   pin_memory: True
   drop_last: True
   
   
   
  

