model_config:
  num_blocks: 15
  embedding_dim: 768
  conv_kernel_size: 7
  conv_mixer_repetition: 20
  patch_size: 16
  n_head: 16
  transformer_encoder_repetition: 10
  dropout: 0.20 # default 0.2
  num_registers: 1 ## This dude is for cls token to be used later!!!
  multiplication_factor: 4 ## NN after attention layers!!!
  output_classes: 1000

trainer_config:
  compile_model: False
  snapshot_dir: "model"
  snapshot_name: "model_1.pt"
  save_every: 1
  total_epochs: 300
  
  
optimizer_scheduler_config:
  optimizer_config:
    lr: 0.0001875  #0.0005*batch_size*gradient_accumulation_steps*GPU/512
    weight_decay: 0.05

  scheduler_config:
    cosine:
      T_0: 300
      eta_min: 0.0000088
    constant_scheduler:
      factor: 0.0001
      total_iters: 2
    linear_scheduler:
      total_iters: 5
      start_factor: 0.0002
  
data:
  train_path:
   root_dir: "~/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/train"
  val_path:
   root_dir: "/home/sahmaran/Desktop/ImageNet/ILSVRC/Data/CLS-LOC/val"
   csv_file: "~/Desktop/ImageNet/LOC_val_solution.csv"
  cache_dir: 

  train_data_details:
   batch_size: 64
   num_workers: 8
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 2
   gradient_accumulation_steps: 8
   
  val_data_details:
   batch_size: 32
   num_workers: 4
   pin_memory: True
   drop_last: True
  
  
